# Generated by Django 3.0.8 on 2021-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210617_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
